version: '3.8'

name: dev-overtime-duo

services:
  devcontainer:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
